# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

jobs:
- job: SAST
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: WhiteSource@21
    inputs:
      cwd: '$(System.DefaultWorkingDirectory)'
      projectName: 'Netflix'

- job: Build
  dependsOn: SAST
  condition: succeeded()
  pool:
    vmImage: ubuntu-latest
  container: maven:3.8.1-openjdk-17-slim
  steps:
  - task: Maven@3
    inputs:
      mavenPomFile: './pom.xml'
      goals: 'package -Dmaven.test.skip=true'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false 
  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: 'ls && pwd && ls'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '/__w/1/s/target/'
      Contents: '**'
      TargetFolder: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)'
      
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId)'
      ArtifactName: 'drop'
      publishLocation: 'Container'
