# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  vmImage: ubuntu-latest
container: maven:3.8.1-openjdk-17-slim

steps:
- task: Maven@3
  inputs:
    mavenPomFile: './pom.xml'
    goals: 'package -Dmaven.test.skip=true'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls && pwd && ls'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'apt-get -y install zip'

- task: ArchiveFiles@2
  displayName: 'Archive files'
  inputs:
    rootFolderOrFile: 'target'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).jar'
    replaceExistingArchive: true
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).jar'
    ArtifactName: 'drop'
    publishLocation: 'Container'
