apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-petclinic2
spec:
  replicas: 3  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      containers:
      - name: web-container
        image: amxcr.azurecr.io/aks-store/petclinic:v1
        ports:
        - containerPort: 8080  # Adjust the port if needed
---
apiVersion: v1
kind: Service
metadata:
  name: petclinic-service2
spec:
  selector:
    app: petclinic
  ports:
    - protocol: TCP
      port: 80       # External port on the service
      targetPort: 8080 # Port on the pod
  type: NodePort
